#CREATED BY ALI ADNAN

import time
def Sleep():
    time.sleep(1.5)
def IntroScene():
    print("")
    print ("UNKNOWN: You're awake")
    Sleep()
    print ("YOU: I am?")
    Sleep()
    print ("UNKNOWN: God I don't think you remember a thing")
    Sleep()
    print ("YOU: What happened?")
    Sleep()
    print ("UNKNOWN: He got to you...")
    Sleep()
    print ("YOU: Who Did?")
    Sleep()
    print ("UNKNOWN: The Master. He Betrayed you")
    Sleep()
    print ("YOU: Oh, He stole the sword aswell")
    Sleep()
    print ("UNKNOWN: THE Sword?")
    Sleep()
    print ("YOU: THE Sword.")
    Sleep()
    print ("UNKNOWN: What's your name partner?")
    global username
    username=input("Type in your name: ")
    print (f"{username}: The Name's {username}, and you are?")
    Sleep()
    print ("ALLOY: I'm alloy, I found you lying in the woods after you were betrayed I assume, Thought you were dead")
    Sleep()
    print (f"{username}: Well then, I suppose I can either continue to lie here")
    Sleep()
    print (f"{username}: Or Avenge myself.")
    Sleep()
    print ("-----------DIALOGUE END-----------")

